// AUTO-GENERATED by scripts/i18n-gen-types.mjs — DO NOT EDIT BY HAND
// 출처: messages/ko.json (ko 가 단일 출처. en 은 i18n:check 로 동기화 강제)
// 갱신: npm run i18n:types (또는 prebuild 시 자동 실행)

interface IntlMessages {
  common: {
    appName: string;
    loading: string;
    save: string;
    cancel: string;
    delete: string;
    edit: string;
    close: string;
    confirm: string;
    back: string;
    next: string;
    search: string;
  };
  auth: {
    login: string;
    logout: string;
    loginRequired: string;
  };
  nav: {
    dashboard: string;
    sites: string;
    customers: string;
    estimates: string;
    schedule: string;
    materials: string;
    settings: string;
  };
  locale: {
    ko: string;
    en: string;
    switchTo: string;
  };
}

declare module "next-intl" {
  // next-intl 의 AppConfig 에 Messages 타입 주입 — t("...") 호출 시 키 자동완성/타입체크.
  interface AppConfig {
    Messages: IntlMessages;
  }
}
