import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import {
  marketingPosts,
  marketingContent,
  threadsAutoRules,
  threadsTemplates,
  sites,
  sitePhotos,
} from "@/lib/db/schema";
import { eq, and, lte, isNull, desc } from "drizzle-orm";

/**
 * POST /api/cron/auto-post
 * 예약된 마케팅 포스트 자동 발행 + 정기 포스팅 규칙 실행
 * Vercel Cron 또는 외부에서 매시간 호출
 */
export async function POST(request: NextRequest) {
  const cronSecret = process.env.CRON_SECRET;
  const authHeader = request.headers.get("authorization");

  if (!cronSecret || authHeader !== `Bearer ${cronSecret}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const now = new Date();
    const results: {
      scheduledPublished: number;
      autoGenerated: number;
      errors: string[];
    } = {
      scheduledPublished: 0,
      autoGenerated: 0,
      errors: [],
    };

    // 1. Publish scheduled posts that are due
    const scheduledPosts = await db
      .select()
      .from(marketingPosts)
      .where(
        and(
          eq(marketingPosts.status, "scheduled"),
          lte(marketingPosts.scheduledAt, now)
        )
      )
      .limit(20);

    for (const post of scheduledPosts) {
      try {
        // Mark as publishing
        await db
          .update(marketingPosts)
          .set({ status: "publishing", updatedAt: now })
          .where(eq(marketingPosts.id, post.id));

        // The actual publish call would be made via internal fetch to /api/marketing/publish/[channel]
        // For now, mark as ready for publish — the publish endpoint handles platform API calls
        await db
          .update(marketingPosts)
          .set({ status: "ready_to_publish", updatedAt: now })
          .where(eq(marketingPosts.id, post.id));

        results.scheduledPublished++;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        results.errors.push(`Post ${post.id}: ${msg}`);
        await db
          .update(marketingPosts)
          .set({
            status: "failed",
            errorMessage: msg,
            updatedAt: now,
          })
          .where(eq(marketingPosts.id, post.id));
      }
    }

    // 2. Process periodic auto-posting rules (정기포스팅)
    const activeRules = await db
      .select({
        rule: threadsAutoRules,
        template: threadsTemplates,
      })
      .from(threadsAutoRules)
      .leftJoin(
        threadsTemplates,
        eq(threadsAutoRules.templateId, threadsTemplates.id)
      )
      .where(
        and(
          eq(threadsAutoRules.isActive, true),
          eq(threadsAutoRules.type, "정기포스팅")
        )
      );

    for (const { rule, template } of activeRules) {
      // Check if enough time has passed since last trigger
      const schedule = rule.schedule as string;
      if (!shouldTrigger(rule.lastTriggeredAt, schedule, now)) continue;

      try {
        if (template) {
          // Generate content from template
          const content = applyTemplate(
            template.contentTemplate,
            template.hashtagTemplate
          );

          const [newContent] = await db
            .insert(marketingContent)
            .values({
              userId: rule.userId,
              workspaceId: rule.workspaceId,
              targetChannels: ["threads"],
              contentType: "인테리어팁",
              title: `자동 포스팅 - ${template.name}`,
              body: content.body,
              tags: content.hashtags,
              status: "draft",
            })
            .returning();

          const [post] = await db
            .insert(marketingPosts)
            .values({
              userId: rule.userId,
              workspaceId: rule.workspaceId,
              contentId: newContent.id,
              channel: "threads",
              body: `${content.body}\n\n${content.hashtags.map((h: string) => `#${h}`).join(" ")}`,
              hashtags: content.hashtags,
              status: "draft",
            })
            .returning();

          results.autoGenerated++;
        }

        // Update last triggered
        await db
          .update(threadsAutoRules)
          .set({ lastTriggeredAt: now })
          .where(eq(threadsAutoRules.id, rule.id));
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        results.errors.push(`Rule ${rule.id}: ${msg}`);
      }
    }

    return NextResponse.json({
      success: true,
      timestamp: now.toISOString(),
      ...results,
    });
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "CRON 실행 중 오류 발생";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

/**
 * Check if a periodic rule should trigger based on its schedule string
 * schedule format: "daily", "weekly", "every_12h", "every_3d"
 */
function shouldTrigger(
  lastTriggered: Date | null,
  schedule: string,
  now: Date
): boolean {
  if (!lastTriggered) return true;

  const elapsed = now.getTime() - new Date(lastTriggered).getTime();
  const hours = elapsed / (1000 * 60 * 60);

  switch (schedule) {
    case "daily":
      return hours >= 24;
    case "weekly":
      return hours >= 168;
    case "every_12h":
      return hours >= 12;
    case "every_3d":
      return hours >= 72;
    default: {
      // Parse "every_Xh" or "every_Xd" format
      const hourMatch = schedule.match(/every_(\d+)h/);
      if (hourMatch) return hours >= parseInt(hourMatch[1], 10);
      const dayMatch = schedule.match(/every_(\d+)d/);
      if (dayMatch) return hours >= parseInt(dayMatch[1], 10) * 24;
      return hours >= 24; // default daily
    }
  }
}

/**
 * Apply a content template with variable substitution
 */
function applyTemplate(
  contentTemplate: string,
  hashtagTemplate: string | null
): { body: string; hashtags: string[] } {
  const now = new Date();
  const dayOfWeek = ["일", "월", "화", "수", "목", "금", "토"][now.getDay()];
  const month = now.getMonth() + 1;

  // Replace template variables
  let body = contentTemplate
    .replace(/\{\{dayOfWeek\}\}/g, dayOfWeek)
    .replace(/\{\{month\}\}/g, String(month))
    .replace(/\{\{date\}\}/g, `${month}/${now.getDate()}`);

  const hashtags = hashtagTemplate
    ? hashtagTemplate
        .split(/[,\s#]+/)
        .filter(Boolean)
        .map((h) => h.trim())
    : ["인테리어", "인테리어팁", "스몰테이블디자인"];

  return { body, hashtags };
}
